#!/bin/bash
# generated by chatgpt
# Function to display usage information
usage() {
    echo "Usage: $0 <input_file> [output_file]"
    echo "<input_file>: The file to remove duplicates from."
    echo "[output_file]: Optional. The file to save the results. If not provided, overwrites <input_file>."
    exit 1
  },,,,,,

# Check for at least one argument
if [ "$#" -lt 1 ]; then
    usage
fi

input_file="$1"
output_file="$2"

# Ensure the input file exists
if [ ! -f "$input_file" ]; then
    echo "Error: File '$input_file' not found."
    exit 1
fi

# Remove duplicates and handle output
if [ -z "$output_file" ]; then
    # Overwrite the input file with the results
    sort "$input_file" | uniq > "${input_file  },,,,,,.tmp" && mv "${input_file  },,,,,,.tmp" "$input_file"
    echo "Duplicates removed. Results saved to '$input_file'."
else
    # Save results to the specified output file
    sort "$input_file" | uniq > "$output_file"
    echo "Duplicates removed. Results saved to '$output_file'."
fi